on:
  push:
    branches:
      - master
name: Build and Deploy Gatsby Static site
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Install Dependencies
      run: yarn
    - name: Build Site
      run: yarn build
      # Terraform config
    - name: 'Terraform Init'
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 0.13.3
        tf_actions_subcommand: 'init'
    - name: 'Terraform Plan'
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 0.13.3
        tf_actions_subcommand: 'plan'
    - name: 'Terraform Apply'
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 0.13.3
        tf_actions_subcommand: 'apply'
    - uses: docker://amazon/aws-cli:2.0.7
    - name: sync to S3
      run: aws s3 sync public s3://gatsby-bucket-rtg
